<a href="https://colab.research.google.com/github/VladAsh7827/-/blob/main/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D1%83_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B8%CC%86_%D0%94%D0%97_1_Google_Colab_%D0%9D%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_1_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание 1. Введение в NumPy и описательные статистики

**Правила:**
* В задачах этого ДЗ все пункты решаются с помощью средств Numpy
* Если условие задачи содержит вопрос, подразумевающий текстовый ответ или вывод, его необходимо давать разёрнуто и подробно. Односложные ответы не будут оценены в полный балл

**Решение оценивается в 0 баллов, если:**
* В коде содержится готовый, непонятно откуда взявшийся ответ (например вместо `print(arr.shape)` написано `print((3,4))`
* Есть подозрения на списывание

In [ ]:
import numpy as np
import scipy.stats as sps

## 1. Базовая работа с массивом 🍭

А. (0,2  балла) Создай двумерный массив `data` следующего содержания:

```
5 2 1 7 3
4 6 8 2 13
1 7 8 7 7
```

 и сразу, при создании, присвой данным тип `np.int32`.

Б. (0,2  балла) Для получившегося массива узнай общее число элементов с помошью средств Numpy двумя разными способами

В. (0,3  балла) Приведи массив к типу `np.float32` и сохрани результат в перменную `data_float`. Возведи значения обоих массивов в степень 110 любым удобным способом. Объясни, чем может отличаться результат арифметических операций до и после приведения

Г. (0,3  балла) Возведи исходный массив `data` в квадрат отличным от пункта 3 способом и объясни, как изменится порядок элементов, если потом применить `.flatten()` и `.reshape(1, -1)`. Почему так произошло?


### 1А (0,2  балла). Создай двумерный массив `data` следующего содержания:

```
5 2 1 7 3
4 6 8 2 13
1 7 8 7 7
```

 и сразу, при создании, присвой данным тип `np.int32`.


**Решение**

In [ ]:
# твоё решение здесь
data = np.array(([5, 2, 1, 7, 3], [4, 6, 8, 2, 13], [1, 7, 8, 7, 7]), dtype=np.int32)

### 1Б (0,2  балла). Для получившегося массива узнай:

#### Общее число элементов двумя разными способами

**Решение**

In [ ]:
# твоё решение здесь
data.size
data.shape

(3, 5)

### 1В (0,3  балла). Создай копию массива. Создай копию массива и сохрани её в переменную `data_float`.



**Решение**

In [ ]:
# твоё решение здесь
data_float = data.copy()

#### Приведи массив к типу `np.float32` и сохрани результат в перменную `data_float`. Возведи значения обоих массивов в степень 110 любым удобным способом.

**Решение**

In [ ]:
# твоё решение здесь
data_float = data.astype(np.float32)
data_float ** 110

/tmp/ipython-input-995214009.py:3: RuntimeWarning: overflow encountered in power
  data_float ** 110


array([[          inf, 1.2980742e+33, 1.0000000e+00,           inf,
                  inf],
       [          inf,           inf,           inf, 1.2980742e+33,
                  inf],
       [1.0000000e+00,           inf,           inf,           inf,
                  inf]], dtype=float32)

In [ ]:
data ** 110

array([[ 1399551081,           0,           1,  -356331695,   768793337],
       [          0,           0,           0,           0, -1218815143],
       [          1,  -356331695,           0,  -356331695,  -356331695]],
      dtype=int32)

#### Объясни, чем может отличаться результат арифметических операций до и после приведения.  



**Решение**

In [1]:
# твоё решение здесь
'''
До применения операции данные будут перезаписываться без ошибки,
а после будет возникать ошибка перегрузки типа данных.
'''

'\nДо применения операции данные будут перезаписываться без ошибки, \nа после будет возникать ошибка перегрузки типа данных.\n'

### 1Г (0,3  балла). Возведи исходный массив `data` в квадрат отличным от пункта 3 способом и объясни, как изменится порядок элементов, если потом применить `.flatten()` и `.reshape(1, -1)`. Почему так произошло?

**Решение**

In [ ]:
# твоё решение здесь

## 2. Аналитика данных 📈

Представь, что ты — аналитик, отслеживающий время ответа сервиса. У тебя есть набор замеров (в миллисекундах), где большинство значений лежат в пределах нормы, но есть явные выбросы:

```
[100, 105,  98, 102, 107,  95, 110, 115, 108, 104, 99, 103, 150, 130, 140, 120, 1000, 1200]
```

А. (0,5 балла) Посчитай для всех 18 замеров:

   * среднее
   * медиану
   * моду
   * стандартное отклонение

Б. (0,5 балла) В наборе данных два последних значений являются выбросами. Сделай срез, убрав два эти два значения и пересчитай те же статистики для «чистых» 16 замеров.

В. (0,5 балла) Посмотри на результаты вычислений в передыдущем пункте и объясни:

   * Почему среднее «врет» при наличии парочки сверхмедленных откликов?
   * Что лучше отражает «типичное» время ответа — медиана или мода — и почему?

Г. (0,5 балла) Стажёр в твоей команде применил к массиву сначала `.flatten()`, а потом `.reshape(6, 3)`. Что ты можешь сказать о таком наборе команд и как ты можешь проинтерпретировать итоговый результат?


In [ ]:
data = np.array([100, 105,  98, 102, 107,  95, 110, 115, 108, 104,
                 99, 103, 150, 130, 140, 120, 1000, 1200])

### 2А (0,5 балла) Посчитай для всех 18 замеров:



#### Среднее  


**Решение**

In [ ]:
# твоё решение здесь
np.mean(data)

np.float64(221.44444444444446)

#### Медиану  


**Решение**

In [ ]:
# твоё решение здесь
np.median(data)

np.float64(107.5)

#### Моду  


**Решение**

In [ ]:
# твоё решение здесь
sps.mode(data)

ModeResult(mode=np.int64(95), count=np.int64(1))

#### Стандартное отклонение  


**Решение**

In [ ]:
# твоё решение здесь
np.std(data)

np.float64(312.7338631101571)

### 2Б (0,5 балла). Сделай срез, убрав выбросы и пересчитай те же статистики для «чистых» 16 замеров.



**Решение**

In [ ]:
# твоё решение здесь
new_data = data[:-2]

#### Среднее  


**Решение**

In [ ]:
# твоё решение здесь
np.mean(new_data)

np.float64(111.625)

#### Медиану  


**Решение**

In [ ]:
# твоё решение здесь
np.median(new_data)

np.float64(106.0)

#### Моду  


**Решение**

In [ ]:
# твоё решение здесь
sps.mode(new_data)

ModeResult(mode=np.int64(95), count=np.int64(1))

#### Стандартное отклонение  


**Решение**

In [ ]:
# твоё решение здесь
np.std(new_data)

np.float64(15.329200076977273)

### 2В (0,5 балла). Посмотри на результаты вычислений в передыдущем пункте и объясни, почему среднее «врет» при наличии парочки сверхмедленных откликов? Что лучше отражает «типичное» время ответа — медиана или мода — и почему?


**Решение**

In [ ]:
# твоё решение здесь
'''

'''

### 2Г (0,5 балла). Словесно опиши, как бы изменилось твоё ощущение данных, если бы ты применил к массиву сначала `.flatten()`, а потом `.reshape(6, 3)`? Представь, что данные относятся к шести отдельным веб-страницам сервиса. На что ты обратил бы внимание, даже не строя графиков? Напиши код и покажи вывод конечного результата. Пошагово объясни, как сработал каждый из методов

**Решение**

In [ ]:
# твоё решение здесь

## 3. Рубрика "Эксперименты" 🧪

Безумный учёный Ржевский и его аспирант Петька проводят эксперимент по скрещиванию кактуса, кальмара и капибары

В ходе эксперимента в течение часа каждые 5 минут измеряется температура с датчика. Всего было проведено 3 серии замеров — температуры непосредственно кактуса, кальмара и капибары. Петька записал результаты в виде вложенных списков Python, но для анализа вам необходимо использовать Numpy.

In [ ]:
[20.1, 20.5, 21.3, 22.0, 23.1, 24.9, 26.9, 28.0, 27.5, 26.3, 24.0, 22.8] # 1 серия (температура кактуса)
[19.9, 20.3, 21.6, 22.3, 24.0, 25.9, 27.2, 29.5, 28.1, 26.0, 23.9, 22.8] # 2 серия (температура кальмара)
[20.0, 20.7, 21.9, 22.8, 24.1, 25.0, 26.8, 23.9, 27.3, 26.5, 24.2, 22.7] # 3 серия (температура капибары)

[20.0, 20.7, 21.9, 22.8, 24.1, 25.0, 26.8, 27.9, 27.3, 26.5, 24.2, 22.8]

А. (0,1 балла) Создай двумерный массив Numpy `exp_data` на основе полученных данных

Б. (0,5 балла) Профессор Ржевский понял, что проводил замеры в градусах Цельсия, а для вычислений ему нужны Фаренгейты. Создай массив `exp_data_F` со значениями, переведёнными в шкалу Фаренгейта. Формула перевода написана ниже (0,5 балла)

$$F = C \cdot \dfrac{9}{5} + 32$$

В. (0,5 балла) Петька решил изучить данные за последние 5 замеров в каждой серии. На основе полученных значений в Фаренгейтах создайте новую переменную `exp_data_last5` размера 3x5, в которой будут лежать последние 5 замеров в каждой серии (0,5 балла)

Г. (0,9 балла) Посчитай стандартное отклонение по всем столбцам среди полученных последних пяти замеров. Какое из значений получилось наименьшим? О чём это говорит? (0,9 балла)

### 3А (0,1 балла). Создай двумерный массив Numpy `exp_data` на основе полученных данных

**Решение**

In [ ]:
# твоё решение здесь
exp_data = np.array(([20.1, 20.5, 21.3, 22.0, 23.1, 24.9, 26.9, 28.0, 27.5, 26.3, 24.0, 22.8],
                     [19.9, 20.3, 21.6, 22.3, 24.0, 25.9, 27.2, 29.5, 28.1, 26.0, 23.9, 22.8],
                     [20.0, 20.7, 21.9, 22.8, 24.1, 25.0, 26.8, 23.9, 27.3, 26.5, 24.2, 22.7]))

### 3Б (0,5 балла). Профессор Ржевский понял, что проводил замеры в градусах Цельсия, а для вычислений ему нужны Фаренгейты. Создай массив `exp_data_F` со значениями, переведёнными в шкалу Фаренгейта. Формула перевода написана ниже

$$F = C \cdot \dfrac{9}{5} + 32$$

**Решение**

In [ ]:
# твоё решение здесь
exp_data_F = exp_data * 9 / 5 + 32
exp_data_F

array([[68.18, 68.9 , 70.34, 71.6 , 73.58, 76.82, 80.42, 82.4 , 81.5 ,
        79.34, 75.2 , 73.04],
       [67.82, 68.54, 70.88, 72.14, 75.2 , 78.62, 80.96, 85.1 , 82.58,
        78.8 , 75.02, 73.04],
       [68.  , 69.26, 71.42, 73.04, 75.38, 77.  , 80.24, 75.02, 81.14,
        79.7 , 75.56, 72.86]])

### 3В (0,5 балла). Петька решил изучить данные за последние 5 замеров в каждой серии. Создайте переменную `exp_data_last5` размера 3x5, в котором будут лежать последние 5 замеров в каждой серии

**Решение**

In [ ]:
# твоё решение здесь
exp_data_last5 = exp_data_F[:, -5:]
exp_data_last5

array([[82.4 , 81.5 , 79.34, 75.2 , 73.04],
       [85.1 , 82.58, 78.8 , 75.02, 73.04],
       [75.02, 81.14, 79.7 , 75.56, 72.86]])

### 3Г (0,9 балла). Посчитайте стандартное отклонение по всем столбцам среди последних пяти замеров. Какое из значений получилось наименьшим? О чём это говорит?

**Какое из значений получилось наименьшим?**

**О чём это говорит?**

**Решение**

In [ ]:
# твоё решение здесь
np.std(exp_data_last5, axis=0)

array([4.26042251, 0.61188234, 0.36986484, 0.22449944, 0.08485281])

In [ ]:
'''
Наименьшим отклонением оказался последний замер кактуса, капибары и кальмара. Это говорит о
том, что температура кактуса, кальмара и капибары примерно одинакова.
'''

'\nНаименьшим отклонением оказался последний замер кактуса, капибары и кальмара. Это говорит о \nтом, что температура кактуса, кальмара и капибары примерно одинакова.\n'